### ISSUE TITLE
invalid signature al cargar ambiente de certificación

### ISSUE THREAD

**Issue by hlatorreg** [TransbankDevelopers/transbank-sdk-nodejs#39]
**Describe el bug**

Ocupando la versión 1.0.2, al tratar de cargar el objeto webPayTransaction del objeto config (con el fin de partir una transacción) se muestra el siguiente error:

```
[
  'invalid signature: the signature value qKmZekhGfy6OBSIJSKHx8NWzJ1QUCANSA0Cu4xz5YSRYviSFBcQRsl/iCq9kONMXU656q2YsHNtJOV3Bk/YzjuiYjceFA5j/0QFXzFgRAdtQqMCu2I+J2NoIyNLDWmIKbifuY8nAZIuNjafwpjraTTDWmKNlwmQYTS5ts53EDZRfvZvFNNxcf87gXva+oER2xPPAoLLp8X1kl6utLt1eHhAXRsILiUtf6CjQHWb8IQh9mppe99MDZ4wo2SVtwP4nY//LhsT24ROopBMfiRFFvFxsw7DyNnjbuHP8wZHs3RJcOSYaXZOHJbTAMVAnyTJC1+30XDouYZ6PsFsiWP/hLA== is incorrect'
]

/WebPay/ms-cruzblanca-webpay/node_modules/tbk_signer/lib/signatureVerifier.js:29
    throw new Error('No result after checking the signature, check the error logs for more information');
          ^
Error: No result after checking the signature, check the error logs for more information
    at module.exports (/WebPay/ms-cruzblanca-webpay/node_modules/tbk_signer/lib/signatureVerifier.js:29:11)
    at /WebPay/ms-cruzblanca-webpay/node_modules/transbank-sdk/lib/webpay.js:138:14
    at /WebPay/ms-cruzblanca-webpay/node_modules/soap/src/client.ts:240:9
    at finish (/WebPay/ms-cruzblanca-webpay/node_modules/soap/src/client.ts:328:7)
    at parseSync (/WebPay/ms-cruzblanca-webpay/node_modules/soap/src/client.ts:351:14)
    at /WebPay/ms-cruzblanca-webpay/node_modules/soap/src/client.ts:513:16
    at Request._callback (/WebPay/ms-cruzblanca-webpay/node_modules/soap/src/http.ts:190:9)
    at Request.self.callback (/WebPay/ms-cruzblanca-webpay/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.emit (node:domain:470:12)
    at Request.<anonymous> (/WebPay/ms-cruzblanca-webpay/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at Request.emit (node:domain:470:12)
    at IncomingMessage.<anonymous> (/WebPay/ms-cruzblanca-webpay/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
    at IncomingMessage.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Para reproducir**

1. Configurar para ocupar webpay en el ambiente de certificación (en producción no hay problema)
2. Requerir el archivo config que contiene las configuraciones asociadas a "transbank-sdk"
3. Cargar el objeto asociado a  webpay.getNormalTransaction()
4. Se ve el error indicado arriba, 

**Comportamiento observado**

Se observa el error

**Comportamiento esperado**

Iniciar la transacción

**Versiones (por favor agrega aquí la siguiente información):**
- SDK:  1.0.2
- Node.js: 16.5.0
- NPM: 7.19.1

El error se observa al tratar de verificar el certificado en transbank-sdk/lib/cert/transbankIntegrationPublicCert.PEM con la libreria tbk_signer

**Comment by ffflabs** [comment]
Estupenda noticia. Tenía hecho un git bisect gigante para cachar en qué momento lo rompí 👍😂
