### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by zagalvelozo** [TransbankDevelopers/transbank-sdk-nodejs#5]
import { Transbank } from 'transbank-sdk';

@Module({
  imports: [Transbank],
  controllers: [AppController],
  providers: [AppService],
});

[Nest] 13836   - 27-05-2020 12:32:07   [ExceptionHandler] Nest cannot create the AppModule instance.
The module at index [0] of the AppModule "imports" array is undefined.

Potential causes:
- A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
- The module at index [0] is of type "undefined". Check your import statements and the type of the module.

Scope [] +7ms
Error: Nest cannot create the AppModule instance.
The module at index [0] of the AppModule "imports" array is undefined.

Potential causes:
- A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
- The module at index [0] is of type "undefined". Check your import statements and the type of the module.

Scope []
    at DependenciesScanner.scanForModules (C:\Users\acer\3D Objects\tbk-service\node_modules\@nestjs\core\scanner.js:44:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DependenciesScanner.scan (C:\Users\acer\3D Objects\tbk-service\node_modules\@nestjs\core\scanner.js:24:9)
    at async C:\Users\acer\3D Objects\tbk-service\node_modules\@nestjs\core\nest-factory.js:80:17
    at async Function.asyncRun (C:\Users\acer\3D Objects\tbk-service\node_modules\@nestjs\core\errors\exceptions-zone.js:17:13)
    at async NestFactoryStatic.initialize (C:\Users\acer\3D Objects\tbk-service\node_modules\@nestjs\core\nest-factory.js:79:13)
    at async NestFactoryStatic.create (C:\Users\acer\3D Objects\tbk-service\node_modules\@nestjs\core\nest-factory.js:30:9)
    at async bootstrap (C:\Users\acer\3D Objects\tbk-service\dist\main.js:97:17)

**Versiones**
- SDK: 1.0.2
- Node.js: 12.17.0 LTS
- NPM: 6.14.4

**Comment by gonzunigad** [comment]
Hi @zagalvelozo. Thanks for the PR. Why did you close it? :)

**Comment by zagalvelozo** [comment]
import * as Transbank  from 'transbank-sdk';
